### ISSUE TITLE
Beacon crash caused by Saecularia-Caudices

### ISSUE THREAD

**Issue by dandin87** [ChiselsAndBits/Chisels-and-Bits#1051]
Placing a beacon with water more than 10 blocks above it causes a server crash whenever that chunk is loaded until the block is removed. Posting here as well since there has been no response on the issue, and its included in Chisel n Bits.
https://github.com/Communi-Suggestu/Saecularia-Caudices/issues/1

**Comment by Vampire2097** [comment]
Im having this issue too. I found that its not just water, but when you place a beacon with any block above it then it crashes.

**Comment by Noobidoo** [comment]
This looks like it's fixed in [1.0.13](https://github.com/Communi-Suggestu/Saecularia-Caudices/releases/tag/1.0.13)

**Comment by marchermans** [comment]
Yep this is indeed fixed

**Comment by dandin87** [comment]
This should not be closed. The version included in Chisel n bits has not updated... So this is still an issue in latest release
