### ISSUE TITLE
Cant create a world

### ISSUE THREAD

**Issue by Plast15** [ChiselsAndBits/Chisels-and-Bits#1138]
I'm working on a modpack to play with some friends and i really wanted to put chisel and bits on but it seems even just having it and the fabric api makes it so i cant create worlds ill go to create one and it gets stuck on 0% until i purposely close it from task manager
I'm playing on 1.20.1 with fabric version 0.14.22 and chisel version 1.4.141

**Comment by Terandox-The-Pineapple** [comment]
Same problem here

**Comment by marchermans** [comment]
I was able to reproduce this and got it fixed in the upcoming update. Curse is reviewing it as we speak

**Comment by Terandox-The-Pineapple** [comment]
Version 1.4.144 - Fabric, Bug still exists. Cant create a World...
