### ISSUE TITLE
Create & C&B Elevator turns invisible

### ISSUE THREAD

**Issue by owochle** [ChiselsAndBits/Chisels-and-Bits#1296]
C&B used on elevator turning invisible when assembling it. I tried removing sodium iris and all but no luck.
I'm on 1.20.1

**Comment by kasperbjerby** [comment]
Happens for me too, but i am afraid it seems like 1.20.1 is dead there has been no new builds for it for 2 years, so i think he has stopped supporting it

**Comment by marchermans** [comment]
Fixed in the latest version for 1.20.1: 20.1.14.
C&B Now requires Create 6

**Comment by kasperbjerby** [comment]
Still happens for me using chisels-and-bits-fabric-20.1.18, is it a mod conflict then?

**Comment by marchermans** [comment]
> Still happens for me using chisels-and-bits-fabric-20.1.18, is it a mod conflict then?

This will never be supported on fabric, sorry

**Comment by kasperbjerby** [comment]
Ahh, sucks.. But thanks
