### ISSUE TITLE
Blocks turning invisible

### ISSUE THREAD

**Issue by xhatz** [ChiselsAndBits/Chisels-and-Bits#241]
Hello!

I am experiencing an issue with the Chisels and Bits mod, but I don't know if it's exactly what is causing the rendering issues or not...

I placed a few chisels and bits blocks near my spawn point, and after some time and after reloading the game, those chisels and bits blocks are turning invisible, and when you walk into them, your character glitches a little. Also the chests near the blocks turned invisible, but are visible again after right-clicking them... and the C&B blocks turn visible again after updating the block where they are placed (by placing another bit)...

I tried updating Optifine, uninstalling it, editing things on my nvidia card, but nothing seems to work... I would really like to know how to fix that, please. We were two playing on my server and it happened for the other player too ^^'.

Thank you and sorry if the text sounds kinda strange, I am french and currently kinda tired ahah xD... Great mod otherwise, keep up your great work Algorithm :3

EDIT:
- When logging out and in again, some of my C&B constructions turn invisible (not all of them, so strange).
- When the chests are invisible and I hold the Chisel in my hand, they turn visible again.
- When logging in again, some of the C&B blocks are just invisible hitboxes, and when I right click them they disappear.

**Comment by xhatz** [comment]
After some tests, I think I have find something that is related to that bug.

After removing the mod **Pam's Harvestcraft (version 1.11.2c)**, the C&B constructions were back! So I don't know what makes the C&B stuff disappear, maybe the crops when they are near, or the fruits, I really don't know.

After re-enabling Pam's harvestcraft, nothing was disappearing, probably because the source of the problem was gone, I will try to see what the problem exactly is.

EDIT: I reinstalled Harvestcraft and most of the crops were gone, but some stayed, but no problem anymore, so I really don't know ahah, but at least we know the source of the problem ^^'.

**Comment by AlgorithmX2** [comment]
Based on your description it sounds like there was a block causing things rendering issues, sounds like it was affecting C&B and the chests... which seems kinda odd.

if you have optifine installed C&B is running in static only mode, which means it renders all of its blocks like a normal block. If you don't have optifine installed C&B can swap between multiple renders, some like chests, some like standard blocks.

I am more confused by the fact that having optifine installed you saw the same issue affect both chests and C&B blocks.

It certainly sounds like something in pams was causing an issue, but I have no idea what it would be, I thought pams used standard models, but I could be wrong.

We will only really know if you manage to track down the block or blocks in question tho.

**Comment by dalgrim** [comment]
I have the same issue; some bits blocks are invisible. running FTB Direwolf20 1.10 pack ver 1.5.1 (release).
Blocks will just disappear and can not be moved through. trying causes player movement glitching.
*I'm not using Optifine.
*No Pams blocks in the area, though Pams is in the modpack.

Let me know what you'd like me to check.  If you msg me I can get you on the server to see for yourself. It is happening in spawnchunk area.

-Brian

**Comment by AlgorithmX2** [comment]
I need someone to try and track down the minimum set of criteria required to reproduce this, and the means to do so.

So hopefully C&B + 1 Mod ( Pams maybe? ) and what block or blocks cause the issue. I can't just toss all of direwolf20 pack into a dev environment and see whats wrong, I also imagine I'd have heard a lot more issues if it that simple.

**Comment by ame-abunai** [comment]
I am having the same exact issue. We have a server that is being privately hosted from my friends computer. We have C&B AND pams harvestcraft on our 1.11.2 server and chests are constantly invisible and our chiseled items disappear after you relog and just cause glitched movement if you go into the area where they were... it seems like PHC and C&B dont get along? Anyone have a resolution!!

**Comment by xhatz** [comment]
Hey, it's me again! And I have some interesting news!

I did a few tries on my server backup, to try and see what could be the problem. After playing a bit, I realized that the crops had nothing to do with that error. After destroying everything from HarvestCraft, everything was back to normal. I placed some crops to see if it was the problem, but nothing was disappearing.

Then when I placed some **traps** (**Ground Trap**, **Water Trap**, ...), some blocks turned invisible, a few chests and some C&B blocks too (but not all of them, it's so strange ahah). So I did a few more tests and this is the result:

- Placing a **trap inside a chunk** (spawnchunk or not) makes **some** chests and C&B blocks disappear (don't know why some blocks only, and it depends on where the trap is placed within the chunk (so strange oO).
- **Chunks next to the trap's one are not affected**.

And... that's all for now, it's really strange and it's really depending on where the trap is placed within it's chunk... I hope this can help!

EDIT: Not only traps are causing the issue, here's the list of blocks that I have found:
- Market
- Ground Trap
- Water Trap
- Apiary
- Presser

Those are all the blocks that have a GUI, only the Shipping Bin is not causing the issue but has a GUI too.

**Comment by AlgorithmX2** [comment]
Thanks for the details I'll try and look into this this weekend, hopefully its fairly simple now that I have a list of blocks to test it with.

And to confirm the issue only manifests with chests when C&B is present? these blocks don't cause an issue with chests by them selves?

**Comment by xhatz** [comment]
Some chests seems to turn invisible even when there is no C&B block near them yup ^^ Just tested.

**Comment by AlgorithmX2** [comment]
Seems like whatever the issue is probably has nothing to do with C&B specifically then, probably a GL State issue with renders in other mods, I'll still look at it when I find a second to test it.

**Comment by AlgorithmX2** [comment]
I was unable to reproduce the issue with just C&B and harvest craft.

Looking at the harvest craft blocks also yielded no additional details, they appear to only render as simple blocks.

Is there a mod in your pack that attempts to visualize contents or something? They are inventories, so it might be related...

I'm not sure where to go from here, except that there is probably something else making the harvestcraft blocks cause a problem.

**Comment by xhatz** [comment]
Just place a bunch of chests and markets inside a chunk and some chests disappear ahah, only with harvestcraft mod even ^^

**Comment by kiomadoushi** [comment]
Probably related to the Leaves issue that was just fixed? Before, when switching from fancy to fast, chiseled leaves that wouldn't update graphics mode turned invisible. That's been fixed now, but maybe it has something to do with that? It's probably unrelated entirely, but at the very least something must be happening that's similar, I'd think.

**Comment by AlgorithmX2** [comment]
I don't think so, according to @xhatz  C&B isn't necessarily even involved.

Has anyone checked to make sure that there were no errors in the logs when this error occurred? I wasn't able to reproduce it in my tests, but I'm starting to think it might just be something going wrong with harvestcraft. And if thats the case it probably needs to be reported there instead.

**Comment by Tenember** [comment]
I'm having the same issue with on a private server with a friend of mine :/

Using Audax Modpack on Tekkit, so HarvestCraft is installed. Randoms chiseled blocks disappearing but hitbox still present.

There is no crash so no crashlog, don't what I could provide to help.

**Comment by AlgorithmX2** [comment]
At this point it just seems like there is some mod, not sure what, that is causing blocks to disappear. And from whit evidence C&B doesn't seem directly involved in the cause, only the symptoms.

Unless someone can track down the source, I'm not sure what to do.

**Comment by Tenember** [comment]
Well, if that can help, I was able to make the blocks concerned reappear by placing a bit inside the block.
For example, I'm not able to place a bit or any block on invisible bits, but if there is air in this concerned block, placing a bit make all of the invisible bits in the block reappear. Tedious.
Blocks disappear again on reconnect on server.
Tried without Optifine and no change.

How can I help track down the source ? Try without mods that could cause the problems to identify a tier mod causing the issue ?
I also have multiple errors in console but none beginning by 'chiselandbits'.

**Comment by AEnterprise** [comment]
i've had similar issues in the past with my multiblocks (while ago) and each time it turned out to be GL leakage from another mod

**Comment by AlgorithmX2** [comment]
Its quite likely that @AEnterprise is right, especially because chests or other blocks can also be affected.

Another mod is Lilly changing some state, and failing to revert their changes.

Trying with less mod and trying to isolate the cause is probably the best option you can take @Tenember it might be difficult to isolate that exact mod, but its about all you can do at this point.

**Comment by Tenember** [comment]
Removed Pam's HarvestCraft, invisibles bits came back. Too bad the issue already had been reported by @xhatz on the Pam's git and no response since 26 days. :/

**Comment by AlgorithmX2** [comment]
@Tenember did you see any errors in your log from pams? I don't know why Pams would be causing that issue, from what I could tell their blocks were pretty simple.

**Comment by Tenember** [comment]
@AlgorithmX2 
Unfortunately, I'm running a modpack and unable to understand all the errors I have. (which is, I think, not a good thing to have that much errors)
I made a pastebin of the console log on server start if you are brave enough : https://pastebin.com/KpfUDArD

But since you were unable to reproduce with just Pam's and c&b, I'm gonna try to see if a third mod is involved.

**Comment by AlgorithmX2** [comment]
I see some packet related issues with astral sorcery, but not much else, what about the client log?

**Comment by Tenember** [comment]
I don't which one you need exactly so here is both : 
[latest.log](https://pastebin.com/zgt1yNWH)
[fml-client-latest.log](https://drive.google.com/file/d/0B5S3ZbLlI3QYYkMxOUR1dTZOWUE/view?usp=sharing)

**Comment by AlgorithmX2** [comment]
```
Caused by: java.lang.NullPointerException
    at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:191) ~[ItemStackHandler.class:?]
    at com.pam.harvestcraft.tileentities.TileEntityWaterTrap.func_145839_a(TileEntityWaterTrap.java:50) ~[TileEntityWaterTrap.class:?]
    at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:333) ~[asc.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[bno.class:?]
    at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[gw.class:?]
    at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[gw.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_73]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
    ... 9 more
```

Might be the issue, seems like pams is throwing an exception when MC sends the chunk. Its likely that this is causing any other TE data in that chunk to get dropped, resulting in unloaded Chiseled blocks, or chests, or any number of things.

**Comment by AEnterprise** [comment]
yes, errors like that will absolutely cause other chunk data to be lost, corruped and/or completely dropped when syncing to the client

i ran into this a few times when experimenting with different ways of handeling multiblock structures, for some reason if there are (or where, it's been a while and i don't do much modding anymore these days due to a lack of free time) errors during chunk sending it just keeps going and tries to make the best of it instead of letting the entire chunk load fail

and unless they changed it the config option from forge to remove erroring tileentities will not help in this case, that only applies when they cause an exception when receiving a tick, not loading them

**Comment by SDUBZ** [comment]
just wondering if this is still being investigated or if pam herself has been notified of this issue?
because this same disappearing blocks is still happening on my server but in certain areas where chisel and bits has been used in conjunction with chisel blocks to make designs

**Comment by AlgorithmX2** [comment]
@SDUBZ This issue was reported some time ago to harvest craft, I even posted on the issue, https://github.com/MatrexsVigil/harvestcraft/issues/258 and someone else later provided a pull request to fix it.

However there has been no changes on the harvest craft side. No comments or merging.

**Comment by AlgorithmX2** [comment]
The harvestcraft looks like it was deleted... and remade, my issue is gone...

I'm just going to assume this has been fixed at some point, it wasn't my issue anyhow.
