### ISSUE TITLE
[1.16.5] Bit Saw Produces Buggy Pieces

### ISSUE THREAD

**Issue by NielsPilgaard** [ChiselsAndBits/Chisels-and-Bits#598]
The Bit Saw produces blocks that don't really work. They render incorrectly and are invisible in the hotbar most of the time.
[Here's a video of the issue.](https://www.dropbox.com/s/wpwfy3c4cz83vfb/jan-27-2021%2016-53-07.mp4?dl=0)

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: chiselsandbits-0.2.10-RELEASE
* Do You have Optifine: No

Original report: https://github.com/NillerMedDild/Enigmatica6/issues/1092

**Comment by TheOldOne822** [comment]
I came to report the same issue. I can add that after seeing it in a large pack I tested it with just Chisels and Bits and still had invisible blocks in inventory. With glass it also doesn't show the ghost block for where it will be placed.


MC Version: 1.16.5
C&B Version: chiselsandbits-0.2.10-RELEASE
Do You have Optifine: No

**Comment by ZuckerSchock** [comment]
You need to install ~~C&B 0.2.8~~ C&B 0.2.9.
~~C&B 0.2.8~~ C&B 0.2.9 seems to be the most bug free for 1.16.5 it seems it only has some issues with placement direction preview.

C&B 0.2.9 seems to have issues with crafting and C&B 0.2.10 seems to have issues with crafting and invisible icons ontop of placement.

**Comment by marchermans** [comment]
@ZuckerSchock Except that that version contains a massive massive memory leak..........

If people have issues: I can not reproduce the stated issues here nor on a server, so I would need some reproductions here to see how you guys trigger this exactly.

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
Maybe its the Forge version ? I use 36.0.14 from 02/02/21 08:35 PM

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
I tried 
forge-1.16.5-36.0.10-installer
forge-1.16.5-36.0.13-installer
forge-1.16.5-36.0.14-installer
Same issues on all of them for me.

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
Is the memory leak in older versions before C&B 0.2.8 present as well ?
The ones before 0.2.8 seem to work for me also.

**Comment by ZuckerSchock** [comment]
@NillerMedDild 
@TheOldOne822 
Which forge version are you using ? 
If you still have problems, switching C&B versions seems to work pretty fluently, had no issues with my world or other mods. It even kept the stuff i built with C&B.

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
I am using Java Version 8 Update 281
with an Intel i7-9700k if that helps.
The issues are pretty noticeable so it has to be something technical outside of the game would be my guess, if you have no issues with 1.6.5 on 0.2.10-RELEASE.

**Comment by marchermans** [comment]
The memory is present in all versions before.
It happens when two or more chiseled blocks are held in the hotbar.
Causing the cache to explode.

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
I have now tried nearly everything i could think of, without much success.

My procedure was:

Close everything,
Change installation,
Start Minecraft Launcher,
Start Forge Version,
Create New Singleplayer World in Creative, (server has the same issues for me)
Give "Stone",
Give "Crafting Table",
Give "Iron Saw",
Put Saw in Table and Stone,
Craft multiple sawed versions of the block.

My issues are: 
Invisible objects in Inventory, Hotbar and in hand, flickering sometimes, maybe dependant on the direction you are facing and or Player Position. Doesn't have to be sawed, also happens with chiseled blocks or builds.

No placement preview of objects, sawed or chiseled.

Issues if crafting multiple instances of a sawed block (First one works as intended 2nd one can cause the 2nd stage of sawing of the block, causing it to craft 2 different items.)

Issues happen on Server and Singleplayer with or without other mods.

My last idea would be that it could be caused by RTX graphics cards. Drivers all up to date for me. Also i havent tested other saws than the Iron Saw but i doubt the result would be different.

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
The only other starting point for you guys would probably be to check what changed from version 0.2.8 and 0.2.9 to 0.2.10 that could cause these issues.

**Comment by marchermans** [comment]
I found something in the code related to how caches and itemstack models are handled

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
Nice, good job, i wish you much success. 👍🏻

**Comment by marchermans** [comment]
Yeah, no success yet.
I fixed that issue.
Still not rendering any quads what so ever.

**Comment by ZuckerSchock** [comment]
Well, every fix is a step in the right direction. Maybe it has something to do with how item id's and block variants are handled ?

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
@NillerMedDild 
@TheOldOne822 

I have done some more testing. On C&B 0.2.10 using the saw once or placing a sawed block on the ground seems to often fix the icons for a short while. 
I wouldnt advice to play C&B 0.2.8 since chiseled bits cant be placed correctly, atleast for me.
My only options are C&B 0.2.9 and C&B 0.2.10 but on 0.2.10 are the items most of the time invisible, basically unplayable. On C&B 0.2.9 the items are visible basically all the time. Crafting multiple items can be broken on both versions. And the placement preview is invisible for me all the time on all versions.

The most playable version for me is C&B 0.2.9.

**Comment by TheOldOne822** [comment]
I've tried forge-1.16.5-36.0.1 and forge-1.16.5-36.0.14

Also it's not RTX graphics cards as I'm using an AMD RX 5600 XT

**Comment by NielsPilgaard** [comment]
I used Forge-1.16.5-36.0.10 iirc.

**Comment by ZuckerSchock** [comment]
@OrionDevelopment 
@TheOldOne822 
@NillerMedDild 

Thanks, i guess we can safely say, that the Forge version and graphics cards manufacturer, as well as architecture of the card has no impact on the issue. I have tried Minecraft 1.6.4 with forge-1.16.4-35.1.4 as well and if i remember correctly the issues were the same. 

I really don't know what else can allegedly cause some people to have these issues and others to not have them. Maybe ram memory ? Guess its a stretch, i don't think there is much more we can do here. All the information that could be useful should have been expressed here. Drivers can also be kind of neglected since different manufacturers have different drivers. OpenGL or some other library or something else could maybe have an impact. But i guess most answers can now only be found in the code of the mod.

I have one last trace though. I believe the source of the issue is at the part of the code where the different variants are saved or loaded in and from memory. Maybe a temporary placeholder. Or whatever is used to get the array of preview icons and different builds. But as @OrionDevelopment already said "related to how caches and itemstack models are handled". 

Maybe the memory can be read and protocolised or some other debugging can take place.

**Comment by ZuckerSchock** [comment]
Maybe it could have something to do with the speed/clock rate of the ram memory or the type, like DDR4 or DDR5.

**Comment by marchermans** [comment]
It is not hardware related.
Or version related

**Comment by NerfDave** [comment]
Hi, it seems nobody is showing evidence of this bug and I believe I'm having a similar issue, perhaps they are related?

https://user-images.githubusercontent.com/80086319/110071926-c7917400-7d31-11eb-84e6-f3262b4e8e1b.mp4

Edit: I should mention that I am using the same version. The footage is from Enigmatica 6, but I have loaded chisel and bits by itself with the same results.

Summary of specs: 1070ti, 32gb DDR4, i7-7700k, windows 10
All drivers up to date

Also interesting to note that throwing sawed pieces on the ground causes fps drops of around 70% (Clip shows ~135 to ~40)

https://user-images.githubusercontent.com/80086319/110072628-f0663900-7d32-11eb-9123-6fefd0b09ae4.mp4

Unfortunately this does make the mod unusable as it is impossible to place any of these blocks.

**Comment by marchermans** [comment]
Fixed in 0.3.0-Release.

**Comment by TheOldOne822** [comment]
Still not working for glass but everything else vanilla works
